#Include config.ahk
#Include wait.ahk
#Include basics.ahk
#Include images.ahk
#Include logger.ahk
#Include nav.ahk
#Include towers.ahk
#Include globals.ahk
#Include select_map.ahk
#Include select_diff.ahk
#Include select_hero.ahk
#Include geraldo.ahk