#Include dark_path.ahk
#Include erosion.ahk
#Include midnight_mansion.ahk
#Include sunken_columns.ahk
#Include x_factor.ahk
#Include mesa.ahk
#Include geared.ahk
#Include spillway.ahk
#Include cargo.ahk
#Include pats_pond.ahk
#Include peninsula.ahk
#Include high_finance.ahk
#Include another_brick.ahk
#Include off_the_coast.ahk
#Include cornfield.ahk
#Include underground.ahk
#Include castle_revenge.ahk
#Include ancient_portal.ahk
#Include last_resort.ahk
#Include enchanted_glade.ahk